version: '2'
services:
  esp-lights:
    image: amcolash/esp-lights
    build: ./
    container_name: esp-lights
    restart: unless-stopped
    network_mode: 'host'
    volumes:
      - ./server/auth/auth.json:/usr/src/app/auth/auth.json
    entrypoint: npm start
